### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by JohannesHoppe** [angular-buch/book-monkey-styles#2]
What about `book-monkey-styles`?

**Comment by fmalcher** [comment]
and maybe add version number (later) sonthat we don't need to maintain backward compatibility

**Comment by d-koppenhagen** [comment]
so probably `book-monkey5-styles`? What do you think?
But this means for future book releases to manage always a separate package. I think it's a bit complicated.
So why not simply name it `book-monkey-styles` and align the major-version number.
Then we can write down in the book to install it via:

```bash
npm i --save book-monkey-styles@5
```

When we will work on BM6, we can simply increase the major-Version and change the text to:

```bash
npm i --save book-monkey-styles@6
```

... and so on

**Comment by fmalcher** [comment]
Sure, you are right, I didn't think of NPM package versions here. Agree!
